### ISSUE TITLE
Add support for extraManifests

### ISSUE THREAD

**Issue by CiucurDaniel** [openzipkin/zipkin-helm#26]
Would it be possible to add a new value called `extraManifests`. As the name implies, it will provide means to deploy extra manifests as an array. 

This is something which already exists in other charts such as the popular [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

The use case for this is, for example, suppose you are using `Istio` on your cluster and you would like to be able to specify a Virtual Service definition to be deployed with the chart used for accessing your zipkin ui.

eg:

```yaml
 # Extra manifests to deploy as an array
  extraManifests: 
    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: zipkin-vs
        namespace: zipkin
      spec:
        hosts:
        - "some-host.com"
        gateways:
        - some/gateway
        http:
        - match:
          - uri:
              prefix: "/zipkin"
          route:
          - destination:
              host: zipkin
              port:
                number: 9411
```

Implementation should be simple:

```yaml
# templates/extra-objects.yaml

{{ range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```
